src/rundd.h, src/wrappedlibasound.c, src/wrappedlibc.c, src/wrappedlibc_private.h, src/wrapper.c, src/wrapper.h, src/x86emu.c, src/x86run.c
* Add fnstsw, lahf, rep movsw instructions
* Fix div function in libc wrapper
* Use dummy error handler in function my_snd_lib_error_set_handler in libasound wrapper
* Add interrupt flag to default emu flags
=> New instructions and other fixes

CMakeLists.txt
Fixed the `NOLOADADDR` option: it can now be enabled (whereas before it was `NOLOADADDR,`, which is different)
=> Fixed the `NOLOADADDR` option

src/librarian.c, src/pathcoll.c, src/run0f.h, src/run66.h, src/rund8.h, src/rund9.h, src/rundc.h, src/wrappedlibc.c, src/wrappedvorbisfile.c, src/x86int3.c, src/x86run.c, src/x87emu_private.c, src/x87emu_private.h
This PR removes all GCC warnings (using GCC 9.1.1 20190503 with `-Wall`) except for all ...`unused`... warnings.
It also fixes some potential bugs, the most critical ones being in `run0f.h` (this one needs to be checked).
=> Remove almost all GCC warnings

rebuild_wrappers.py
Python 2 support ends in 2020 (Jan 1), so instead of forcing the use of Python 2, it's better to add support for Python 3
=> Fix wrapper generator to work with python2 and python3

src/emu/x86run_private.h
Currently building with O0 causes these functions to fail linking.
=> Fix undefined reference to inline functions when building with O0

src/emu/run0f.h, src/include/regs.h
This PR fixes the PSRAQ instruction, by using signed registers instead of unsigned.
=> Fixed the PSRAQ instruction

src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedlibx11_private.h
With these patches, [Arkos Tracker](http://www.julien-nevo.com/arkostracker/) now works.
It seems to runs fine, with nothing obviously broken.
=> Add some wrapped functions for Arkos Tracker 2

src/emu/x86run.c
Used by exception handlers and TLS in win32
=> Implement some FS opcodes used in windows dlls

CMakeLists.txt, cmake_uninstall.cmake.in
Just in-case somebody needed to uninstall the program.
=> Create an uninstall target

CMakeLists.txt
It's the same as RPI2, without the extra RPI definitions. ;-)
(We can use ASM flags too.)
=> Clean up Gameshell section

src/elfs/elfloader.c
Some compilers (like the one on the GameShell) need this to be included or you get undefined references to "major," "minor," and "makedev."
The result is a build failure.
=> Include sysmacros.h in elfloader.c

src/main.c, src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedlibc.c, src/wrapped/wrappedlibc_private.h
This adds the option to fix 64bit inodes (BOX86_FIX_64BIT_INODES). For details of the problem, read [this article](https://www.mjr19.org.uk/sw/inodes64.html).
For now only stat functions are fixed. Functions readdir and readdir_r should also be fixed, but I'm not sure how to do it, because they are defined as weak symbols (GOW). If i define them as GOM, that changes them to strong symbols.
=> Add option to fix 64bit inodes

USAGE.md, src/wrapped/wrappedlibc.c, src/wrapped/wrappedlibc_private.h
This continues the last pull request (#123).
=> Fix 64bit inodes in readdir and readdir_r functions

src/emu/x86syscall.c, src/main.c, src/wrapped/wrappedlibc.c, src/wrapped/wrappedlibc_private.h
Older versions of glibc (like the one on Pandora) don't have include sys/auxv.h, but include linux/auxvec.h contains definitions used by box86.
Older versions of glibc also don't have recvmmsg and sendmmsg, so I replaced them with my_ versions.
=> Allow compilation with older version of glibc

rebuild_printer.py, src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h
This PR fixes the printer generator for ARM (no shift) instructions with an optional rotation or other optional
=> Fixed the U/SXT* opcodes print (and probably others too)

rebuild_printer.py
This PR corrects the behaviour of the ARMs and ARM$ instructions in the printer generator (ARMs for forcing shifts with immediates only, ARM$ for forcing shifts with registers only).
=> Fixed the ARMs and ARM$ instructions type for the printer

rebuild_printer.py, src/dynarec/arm_printer.c
This PR fixes all `ARMS` instructions in the printer generator (fixes `e0060691`, for instance; before: `AND r0, r6, r1, lsl r6`; after: `MUL r6, r1, r6`).
=> Fixed ARMS (ARM shifted) instruction category

src/dynarec/arm_instructions.txt, src/dynarec/arm_printer.c, src/dynarec/last_run.txt, src/libtools/signals.c
This PR fixes the `VMOV.F32 <register> <immediate>` instruction (register from a double register to a single one) and the build on unrecognized architecture in `libtools/signal.c` (`undeclared variable pc`).
=> Dynarec printer fix

src/elfs/elfparser.c
This PR adds an explicit error message when using a 64-bits ELF (instead of 32-bits).
=> Explicit error message when having 64-bits ELFs

CMakeLists.txt
libstdc++.so.5 is Included in x86libs but not copied to /usr/lib/i386-linux-gnu when 'make install'ing.
=> Update CMakeLissts.txt to copy libstdc++.so.5

README.md
I did some language fixes in README. During this I took some liberties to improve consistently, like always writing Box86 with a capital B. I am not sure whether you have a preferred way to stylise it, but as it is prior to this PR the README mixes box86 and Box86 heavily, and I decided to go with the latter. If you prefer it to always be written box86 with a lowercase b I can change it to be so.
=> Language fixup in README

src/wrapped/wrappedlibc_private.h
Needed for wine from Debian testing.
=> Add a wrapped function for __cmsg_nxthdr

src/main.c
sysconf() is part of unistd.h, and src/main.c uses it. However, this
source code file only includes <unistd.h> when DYNAREC, makes
non-dynarec build fail for missing _SC_PAGESIZE macro.
Move the inclusion of <unistd.h> out of #ifdef DYNAREC.
=> Fix compliation of non-dynarec build

src/wrapped/wrappedglib2_private.h
=> wrap g_utf8_skip in glib, which is a pointer to an array of char

src/include/pathcoll.h, src/main.c, src/tools/pathcoll.c
LD_LIBRARY_PATH should be able to override system libraries, this is the
behavior of ld-linux.so.
=> prepending LD_LIBRARY_PATH

src/dynarec/dynablock.c, src/include/khash.h
Accessing the value of a kh_set (which has no values set) is an
undefined behavior, which may make monsters to appear.
Add a kh_foreach_key macro that do not touch values at all, and use it
when ennuerating marks in dynablock, to prevent SIGSEGV of accessing
non-existent values.
=> dynablock: do not access value when foreach on marks

runTest.cmake
Test10 currently only passes after "make install" (no regard to x86lib directory needed) or we build directly inside box86 folder.
This change make sure x86lib folder is properly located so that we can also "ctest" inside build folder after compile without "make install".
=> Make test10 more robust

src/dynarec/arm_instructions.txt, src/dynarec/arm_printer.c, src/dynarec/last_run.txt
This PR moves the VFPU `VMOV` instruction above an `INVALIDATE` instruction to the ARM opcodes printer generator (fixes a `???` shown in https://github.com/ptitSeb/box86/issues/167#issuecomment-668860278).
=> [DYNAREC] Fixed the four VMOV VFPU instructions printer

rebuild_printer.py, src/dynarec/arm_printer.c
This PR fixes the printer in various places:
- all NEON variable size opcodes possibly operating on 64 bits (with an immediate 6-bits and a Long bit). This should fix `F2 98 E5 5E`.
- the `VSHL.<dt>` instruction (maybe other opcodes above and below are wrong too...). This should fix `F2 00 14 01`.
- the `VMOV.<dt> <Rt>, <Dn[x]>` instruction. This should fix `EE D1 4B 10`.
=> Various printer fixes

rebuild_printer.py, src/dynarec/arm_instructions.txt, src/dynarec/arm_printer.c, src/dynarec/last_run.txt
This PR fixes some instructions:
- Any instructions with a constant (fixes `E2801F9E ADD r1, r0, #0x278`)
- The `VMOVL` and `VQMOVN` instructions (`F3B68288`)
- The `VSHRN` instruction (`F2D02810`)
=> Fixed some instructions printer

COMPILE.md
Here is all the commands it takes to compile & install box86 on a Raspberry Pi.
Using `make -j24` is much faster - it compiles in about 1/6 of the time as it does originally.
=> Optimize compilation & full install commands

src/wrapped/wrappedlibncurses.c, src/wrapped/wrappedlibncurses6.c, src/wrapped/wrappedlibncursesw.c
A call to vmprintw is made, which is a non-existent function.
Presumably, vwprintw is meant to be called instead.
=> Fix presumable typo in wrappedlibncurses files

src/wrapped/wrappedd3dadapter9.c, src/wrapped/wrappedd3dadapter9_gen.h
This means both x86 and ARM code can have the right function pointers
at the same time, allowing a hack in Gallium Nine to be removed.
=> Create a fake IDirect3D9 object instead of changing the vtable

archlinux/PKGBUILD-RPi4B, archlinux/PKGBUILD-arm, archlinux/PKGBUILD-gameshell, archlinux/PKGBUILD-odroid, archlinux/PKGBUILD-pandora, archlinux/PKGBUILD-pyra, archlinux/PKGBUILD-raspberrypi, archlinux/PKGBUILD-x86, archlinux/README.md
I've added an RPi4B PKGBUILD right now, but planning for the other platforms too. Just give me an info about the `depends()` and `optdepends()` (I figured myself out which `makedepends()` are needed).
=> PKGBUILDs for Arch Linux.

CMakeLists.txt
#244 broke the install target because `system/box86.conf` should now be taken from the build directory, sorry for that.
=> Fix install target after previous change

COMPILE.md, README.md, src/box86context.c, src/custommem.c, src/tools/fileutils.c, src/wrapped/wrappedlibc.c, src/wrapped/wrappedxml2.c
Removed some redundant if elses, fixed some typos in the documentation and reworded some sentences.
=> Simplified code

CHANGELOG.md, LICENSE, README.md, USAGE.md, src/libtools/sdl2rwops.c, src/tools/callback.c, tests/extensions/mmx.c
I also changed the copyright year.
=> Clarified a bit more documentation, fixed a lot of typos and removed some redundant codes.

README.md
First of all many thanks for your great work! 🙏
The "Remember password" feature works only if libnm is installed, otherwise the next starts hang infinite.
Steam can be started with the small mode mini games list opened directly by using the "+open steam://open/minigameslist" command line arguments.
The Steam for Linux issues have been sorted into a listing, to get a better overview and separation between each issues. The Steam for Windows note has been mode below the list.
_If you want to keep the block text style, I can revert this. Found it a bit better readable, also since the single linebreaks in code are not translated into linebreaks in HTML._
A few minor spelling and wording fixes have been applied: "Steam" always with capital S, full sentences, aligned package install instruction …
=> Update notes about Steam

src/dynarec/arm_instructions.txt, src/dynarec/arm_printer.c, src/dynarec/last_run.txt
This PR fixes opcodes `E6FF1F3A` and `E16F7F11` (among others of the same kind).
=> Added the CLZ and RBIT opcodes

docs/README.md
It seems that original link has been broken earlier and I haven't checked if it points to the proper file earlier.
This pull request should change that.
=> Fixed link to "x86primop.c".

docs/README.md
- The grammar in some parts wasn't the best, I did some minor changes
- I moved installation instructions up since most people on the repo are more interested in installing it than reading a solid block of documentation
- pi-apps plugs since much easier to click 2 click install than figuring out how to compile box86
=> Move install instructions higher up and add pi-apps mention

CMakeLists.txt
=> [CMAKE] Fixed builds with '.c' in the path

src/wrapped/wrappedd3dadapter9.c
A couple of games (such as Minetest) end up using the internal vtable as well. The Gallium Nine frontend to Mesa does not use the internal vtable at all, so it is safe to just switch it to the bridged functions.
=> Set the internal vtable for D3D9 structs

src/emu/x86primop.h
```c
// gcc box86_test.c -o box86_test
#include <stdio.h>
__attribute__((naked)) int foo()
{
__asm(
"movl $0xFFFFFFFF, %eax\n\t"
"addl $1, %eax\n\t"
"incl %eax\n\t"
"pushf\n\t"
"pop  %eax\n\t"
"ret\n\n"
);
}
int main()
{
printf("eflags: 0x%08x\n", foo());
return 0;
}
```
=> Fixed INC/DEC (for lazy flags)

.github/workflows/release.yml, CMakeLists.txt
Change the temporary file name of each test in order to prevent the conflict when running ctest with multiple processes enabled.
Fix the typo of CMakeLists.txt
=> Making ctest -j$(nproc) work as intended and fix a typo in github action configuration

pkgbuilds/PKGBUILD-rk3399
This PR makes some changes & fixes to the Arch Linux PKGBUILD for the RK3399:
* Fixes an apparent copy-paste mistake in the `package()` step;
* Sets `-DCMAKE_INSTALL_PREFIX=/usr` using CMake, so that the step moving the files from `/usr/local` is no longer necessary.  This also fixes the `/etc/binfmt.d/box86.conf` file, which otherwise still points to `/usr/local/bin/box86`.
* Runs `cmake` as part of the build, instead of in the prepare stage, and runs it using the `-B ... -S` options, as recommended in https://wiki.archlinux.org/title/CMake_package_guidelines#Specifying_directories
* Removes the `-j` flag from `make`, as in Arch Linux this is something that is normally set via `MAKEFLAGS` in [makepkg.conf](https://man.archlinux.org/man/makepkg.conf.5) instead.
I think it could be a good …
=> Fix rk3399 PKGBUILD

CMakeLists.txt
Hi,
I was trying to compile box86 on a  on a RockPro64 in a a 32-bit (armv8l) Arch Linux chroot (the main OS is Manjaro, but I'm using a chroot because AFAIK there isn't an easy way to set up multilib/multiarch on Manjaro). 
I ran into trouble if I used `-DRK3399=1` because CMake tries to use a specific gcc binary (`arm-linux-gnueabihf-gcc`).   To get around this, I modified the CMakeFile to only override the `CMAKE_COMPILER` variable if CMake reports that it is running on `aarch64`.
I used [cmake_host_system_information](https://cmake.org/cmake/help/latest/command/cmake_host_system_information.html) for this, because the `CMAKE_HOST_SYSTEM_PROCESSOR` variable otherwise doesn't get set until after running `project()`, which seems too late.
I was thinking it might even make sense to just …
=> Don't use cross-compile GCC on 32-bit systems

CMakeLists.txt, src/wrapped/wrappedlibc.c
It looks like the Android support from https://github.com/ptitSeb/box86/pull/372 stopped compiling at some point, so this PR fixes it. The `on_exit()` function doesn't exist on Android, and the `ANDROID` C preprocessor macro wasn't being defined.
=> Fix Android build

debian/copyright, debian/lintian-override, debian/rules, debian/source/format, docs/COMPILE.md
This pr is to prevent the following error from occurring:
```
make[1]: Leaving directory '/home/pi/Downloads/box86/obj-arm-linux-gnueabihf'
dh_installdocs
dh_installchangelogs
dh_perl
dh_link
dh_strip_nondeterminism
dh_compress
dh_fixperms
dh_missing
dh_strip
strip: Unable to recognise the format of the input file `debian/box86/usr/lib/i386-linux-gnu/libgcc_s.so.1'
dh_strip: error: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/box86/usr/lib/i386-linux-gnu/libgcc_s.so.1 returned exit code 1
dh_strip: error: Aborting due to earlier error
make: *** [debian/rules:6: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```
=> Various packaging improvements

postinst
"systemctl restart systemd-binfmt" can only succeed when systemd is the used init system and when the binfmt_misc kernel module is available. The kernel module may not be available right after a kernel upgrade or within a container where it needs to be loaded on the host. 
The common check for whether systemd is used or not is to check for the directory "/run/systemd/system" which is hereby added.
Since modprobe may not be available and within a container always fails (regardless whether the host provides it), the service restart is allowed to fail without failing the postinst script and hence the package install. If the service restart fails, Box86 support in binfmt becomes effective on next system restart, given binfmt_misc is generally available. Furthermore binfmt is a convenience …
=> Make postinst script failsafe

install_steam.sh
I’ve added the missing shebang at the beginning and also made the script a bit easier to read in my opinion.
=> Various improvements to install_steam.sh

install_steam.sh
this can remove lots of headaches when installing Steam on a 64 bit OS like Raspberry Pi OS (64 bit)
=> automatically install 32 bit libraries if 64 bit OS is detected in install_steam.sh 

docs/COMPILE.md
to make compile/use easier for new users (regarding https://github.com/ptitSeb/box86/issues/465 & https://github.com/ptitSeb/box86/issues/682). Also tried to simplify comments/code a little in the RPi sections
=> Add libc6:armhf install to RPi4 aarch64 build info

src/dynarec/dynarec_arm_66f0.c, src/dynarec/dynarec_arm_pass0.h
https://github.com/ptitSeb/box86/issues/598#issuecomment-1138251631
=> Add atomic add opcodes

install_steam.sh
disables the new react ui because the browser isn't available for now and passes the additional command line arguments to the main client
=> steam: disable modern login and pass arguments to client

src/dynarec/dynablock_private.h
instsize_t uses 1 byte acturlly, while alloced 4 bytes before.
=> Modify sizeof(instsize_t) to 1 byte

docs/COMPILE.md
On 64bit OS's the installing the `box86` package installs an old version that has the arch set to `arm64`.
To get the latest version, the `box86:armhf` package has to be installed.
I'll remove the bad package from my repo, but the note still applies.
=> Docs: Add note about installing the correct package from my apt repo on arm64.

install_steam.sh
fix error like
```
dbus[8661]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.
D-Bus not built with -rdynamic so unable to print a backtrace
```
ref:
https://github.com/diasurgical/devilutionX/issues/20
https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1775067
=> Ignore steam dbus warning

debian/rules, docs/COMPILE.md
Debian package maintainers typically prefer using a .zip of the release of software instead of pulling from the master source tree to build their package.
=> add -dnogit=1 flag to debian rules

docs/COMPILE.md
CMake needs it to be `-DARM64=1` instead of `-DARM64`
=> Fix ARM64 Compile Instructions

docs/COMPILE.md
add-key(8) is deprecated and causes warnings to be reported when running apt-get update after adding the repo.
=> docs/COMPILE.md: Use trusted.gpg.d

src/wrapped/wrappedlibjpeg62.c
Wine use compress_ptr as a member of custom record struct, and this struct will be used in libjpeg62's callback, so wrappedlib need save it in jumpbuf_helper
=> Fix libjpeg62 wrapping error

docs/COMPILE.md
=> Add more info about neon vfpv3 to COMPILE.md

CMakeLists.txt, src/wrapped/generated/functions_list.txt, src/wrapped/generated/wrappedlibmtypes.h, src/wrapped/generated/wrapper.c, src/wrapped/generated/wrapper.h, src/wrapped/wrappedlibm.c, src/wrapped/wrappedlibm_private.h
This PR rewrites fesetround and fegetround to set and get the rounding mode in x86emu, and applies the rounding mode on rounding functions (`{,l,ll}rint{,f,l}` and `nearbyint{,f,l}`). Test24 (feround) can pass with this patch.
The rounding mode can also be applied on other math functions if needed.
=> Set rounding mode for some rounding functions of libm

src/main.c
Try to make box86 support _RCFILE env like box64
https://github.com/ptitSeb/box64/blob/main/src/core.c#L1595
=> feat: add BOX86_RCFILE support

install_steam.sh
Fixes #945 and probably other steamwebhelper-related issues.
Fixes :
$@ was not escaped so it was not included in the steam launch script. Which means that any parameter were ignored when starting steam.
Added libibus-1.0-5 package that is required by newer versions of steam. I didn't had to specify armhf on Pi 5 so I don't know if it's required for other platforms?
=> Fix for Steamwebhelper failing to start.

pkgbuilds/PKGBUILD-rk3xxx
Code was taken from box64's PKGBUILD-rk3xxx
=> build: fix PKGBUILD-rk3xxx, _rkmodel was never set

docs/USAGE.md, rebuild_printer.py, src/dynarec/arm_instructions.txt, src/dynarec/arm_printer.c, src/dynarec/last_run.txt, src/include/debug.h, src/main.c, src/tools/my_cpuid.c, src/tools/rcfile.c, src/wrapped/wrappedlibc.c
This PR backports the `BOX86_MAXCPU` env. variable.
It also adds the `ADR` ARM instruction to the `arm_instructions.txt` generator input and rebuilds the `arm_printer.c` file.
Fixes the complaint in https://github.com/ptitSeb/box86-compatibility-list/issues/48#issuecomment-2229075470.
=> [MAXCPU] Added support for maxcpu (backport from box64)

pkgbuilds/PKGBUILD-rk3xxx
Went to compile on my PinePhone Pro ( RK3399 ) and noticed a syntax error from a missing space.
=> Fix missing space in PKGBUILD-rk3xxx causing syntax error

debian/changelog
Bump version in Debian changelog file, to generate .deb package with 0.3.8 in it.
=> Bumped version to v0.3.8

src/main.c
This resolves funny crash if there's no '8' in argv[0].
=> Fix crash with incorrect argv[0]: rewrite it only if "box86" is present
